publishDir = "docs"
baseurl = "http://julieandchad.uk"
title = "Julie and Chad"
theme = "dimension"
languageCode = "en-uk"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '1 June 2019, Pollokshields Burgh Hall, Glasgow'
  logo = "fa-heart"
  copyright = "Julie Ashcroft and Chad Allen"
