publishDir = "docs"
baseurl = "http://julieandchad.uk"
title = "Julie and Chad"
theme = "dimension"
languageCode = "en-uk"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = 'The event of the season'
  logo = "fa-diamond"
  copyright = "Untitled"
